### ISSUE TITLE
[1.9]Client crash when using a hoe on grass

### ISSUE THREAD

**Issue by kwpugh** [DrManganese/ender-crop#1]
What I did: made a wooden hoe and right-clicked on grass to plant some seed

What happened:  Client crash, server just threw an error

Crash report:  http://pastebin.com/raw/9ZQY3gGV

Using Forge 1811 and endercrop 1.2

**Comment by DrManganese** [comment]
Thanks for the feedback! It seems like I've fallen behind on forge versions. New build with forge 1811 on curse soon.
