### ISSUE TITLE
bump to 1.18.2  will submit PRs

### ISSUE THREAD

**Issue by BrewingCoder** [DrManganese/ender-crop#13]
I can submit PRs to bump to 1.18.2 ;  would love to do it if you're interested.

would just need you to push current 1.16.5 into a branch.

For guidance would like to know if you want to stick to 100% forge or do a multi-platform forge/fabric.

If you're not interested in maintaining repo let me know and I can just fork and publish from there.

-BrewingCoder

**Comment by DrManganese** [comment]
Thanks for the offer, however, I just started work on the 1.18.2 port last weekend. Hoping to get it done soon!
