### ISSUE TITLE
Latest Version crash

### ISSUE THREAD

**Issue by DelviousCrafts** [DrManganese/ender-crop#20]
Crash on startup with the latest version. Appears that a 1.20 version was released as compatible with 1.19.2 on CurseForge. Not sure if this is supposed to, in fact, be compatible, or if this was in error which would explain the crash using 1.19.2 version.

[Latest Log](https://gist.github.com/DelviousCrafts/cc5c4eee306f5e39bc3d505e193c6134)

[Crash Report](https://gist.github.com/DelviousCrafts/796e0488aeddb8ea70a07c773e41ae25)

Versions: 
- Minecraft: 1.19.2
- Forge: 43.2.21
- Ender Crop: 1.7.0

**Comment by DrManganese** [comment]
The version was indeed only meant for 1.20. That's what I get for hardcoding.
