### ISSUE TITLE
Detecting wrong light level

### ISSUE THREAD

**Issue by Dragnier** [DrManganese/ender-crop#3]
The crop seems to be detecting the ambient light level from the sun rather than the block light level from torches and such. I have a building that shows 0 light level for block light on the inside but the crop still says it can't grow according to The One Probe tooltip. It states the light is >= 7 despite the 0 block light level.

**Comment by DrManganese** [comment]
Could you give me the minecraft/forge/mod versions please.

**Comment by Dragnier** [comment]
MC: 1.10.2
Forge: 12.18.3.2221
Mod: 1.9.4-1.3.1 (only option from Curse launcher)

**Comment by DrManganese** [comment]
I just tested it in the curse launcher with your versions and this setup seems to work just fine.
![image](https://i.imgur.com/QvRleyL.png)
Maybe a screenshot of the building with the debug screen could help?

**Comment by Dragnier** [comment]
Nevermind, I figured out the issue. There was a block that is apparently transparent to sky light that I thought was supposed to be solid. Not your issue. I'll close this now; sorry for the inconvenience.
