### ISSUE TITLE
Ender crop not growing

### ISSUE THREAD

**Issue by poboy975** [DrManganese/ender-crop#4]
Like the title, I've got an ender seed in a tilled farmland, but it's not growing at all. No bonebeal, no ring of growth, no wand of acceleration either. I've planted several times. I've also got an actually additions worm on the farmland as well. Minecraft 1.12 forge version 14.21.1.2443 ender crop 1.12-1.3.4

**Comment by DrManganese** [comment]
On farmland the crop needs a light level below 7 to grow. So make sure it's in a dark room. (Or just put a solid block on top of it)

**Comment by poboy975** [comment]
That worked, thanks!
