### ISSUE TITLE
[Feature Request] Tinker Tool Integration

### ISSUE THREAD

**Issue by Darkosto** [DrManganese/ender-crop#9]
Hello!

Would you consider adding support for Tinkers' Construct Tools (mattock)? Or possible allowing a config option to disable needing unbreaking on the tool for tilled end stone.

MC: 1.12.2
Forge: 2739
Ender Crop: 1.5.1

Thanks!
Darkosto

**Comment by DrManganese** [comment]
Thanks for the suggestion, I will certainly add a config option for the unbreaking, and I'll look into the tinker tools.
